include:
  - compose-zookeeper.yml
services:
  clamav:
    image: clamav/clamav:stable_base
    ports:
      - "3310:3310"
    volumes:
      - ./temp/clamav:/var/lib/clamav
    platform: linux/amd64
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./temp/db:/data/db
